services:
  tailor-mysql:
    image: mysql:8.4
    container_name: tailor-mysql
    restart: on-failure
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    ports:
      - "3307:3306"
    volumes:
      - tailor-mysql-data:/var/lib/mysql
    networks:
      - tailor-services

  tailor-adminer:
    image: adminer:latest
    container_name: tailor-adminer
    depends_on:
      - tailor-mysql
    environment:
      ADMINER_DEFAULT_SERVER: tailor-mysql
    ports:
      - "8888:8080"
    networks:
      - tailor-services

  tailor-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: tailor
        uid: 1000
    image: tailor-app
    container_name: tailor-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./.dockerfile/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - tailor-mysql
    networks:
      - tailor-services

  tailor-webserver:
    image: nginx:alpine
    container_name: tailor-webserver
    restart: unless-stopped
    ports:
      - "8100:80"
      - "8143:443"
    volumes:
      - ./:/var/www
      - ./.dockerfile/nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - tailor-app
    networks:
      - tailor-services

networks:
  tailor-services:
    driver: bridge

volumes:
  tailor-mysql-data:
